name: insomnia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  image_picker: ^1.0.0
  carousel_slider: ^4.2.1
  webview_flutter: ^3.0.4
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/img/

  fonts:
    - family: Gaegu
      fonts:
        - asset: assets/font/Gaegu-Bold.ttf
        - asset: assets/font/Gaegu-Light.ttf
        - asset: assets/font/Gaegu-Regular.ttf
  

  uses-material-design: true
